### ISSUE TITLE
Please update to spt3g 424054 or later

### ISSUE THREAD

**Issue by mhasself** [simonsobs/spt3g-docker#5]
so3g would greatly appreciate the efficient G3VectorTime conversions!

https://github.com/CMB-S4/spt3g_software/commit/42405455d55f74947bdf6feb9dd135772628091b

Note that even more recent spt3g_software has an "install" target added.  I think that doesn't break old-style build+use.

**Comment by BrianJKoopman** [comment]
These builds happen automatically. All available tags can be found on Docker Hub: https://hub.docker.com/r/simonsobs/spt3g/tags?page=1&ordering=last_updated

We are still using the old build+use style, let me know if that's broken.

**Comment by mhasself** [comment]
Understood, thanks!
